enable-magisk-update = false # set this to false if you do not want to receive update JSON for modules (ignored in APK-only builds)
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[GooglePhotos]
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://bracuexam.lamppost.org.bd/photos.apk"
build-mode = "apk"
included-patches = "'com.google.android.apps.photos.nexus_preload' 'com.google.android.apps.photos.NEXUS_PRELOAD' 'com.google.android.feature.PIXEL_2021_EXPERIENCE' 'com.google.android.feature.PIXEL_2022_EXPERIENCE'"
arch = "arm64-v8a"

[Messenger]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
