name: 'Release APK'
description: 'Release the patched APK'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  app_name:
    description: 'Name of the app being released'
    required: false
    default: 'APK'
runs:
  using: 'composite'
  steps:
    - name: Generate release info
      shell: bash
      id: changelog
      run: |
        echo "First install [MicroG-RE](https://github.com/WSTxda/MicroG-RE/releases/download/5.12/microg-release.apk) if you haven't already for Google Photos, YouTube, and YouTube Music APKs. Maintained by [Sabbir Bin Abbas](https://facebook.com/Sabbirba10)." >> "$OUTFILE"
    - name: Set release date (UTC)
      shell: bash
      id: release_date
      run: |
        # Produce both machine-friendly (ISO) and human-friendly date strings
        echo "date_iso=$(date -u +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
        echo "date_pretty=$(date -u +%d %B %Y)" >> "$GITHUB_OUTPUT"

    - name: Create GitHub Release and upload assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.release_date.outputs.date_iso }}
        name: ${{ steps.release_date.outputs.date_pretty }}
        body: ${{ steps.changelog.outputs.body }}
        files: ./release/*.apk
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
