name: CI
on:
  schedule:
    - cron: '*/05 * * * *' # every 5 minutes (UTC)
  workflow_dispatch:
permissions: write-all

jobs:
  trigger-build:
    uses: sabbirba/rebuild/.github/workflows/build.yml@main
    with:
      org: ReBuild
    secrets: inherit
