name: CI (every 10 minutes)
on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes (UTC)
  workflow_dispatch:

jobs:
  trigger-build:
    uses: ./.github/workflows/build.yml
    with:
      org: ReBuild
